"""
This type stub file was generated by pyright.
"""

import argparse
from contextlib import contextmanager

VERSION = ...
DEFAULT_ROLES_PATH = ...
DEFAULT_RUNNER_BINARY = ...
DEFAULT_RUNNER_PLAYBOOK = ...
DEFAULT_RUNNER_ROLE = ...
DEFAULT_RUNNER_MODULE = ...
DEFAULT_UUID = ...
DEFAULT_CLI_ARGS = ...
logger = ...

class AnsibleRunnerArgumentParser(argparse.ArgumentParser):
    def error(self, message): ...

@contextmanager
def role_manager(vargs): ...
def print_common_usage(): ...
def add_args_to_parser(parser, args):  # -> None:
    """
    Traverse a tuple of argments to add to a parser

    :param argparse.ArgumentParser parser: Instance of a parser, subparser, or argument group

    :param tuple args: Tuple of tuples, format ((arg1, arg2), {'kwarg1':'val1'},)

    :returns: None
    """
    ...

def main(sys_args=...):  # -> int | None:
    """Main entry point for ansible-runner executable

    When the ```ansible-runner``` command is executed, this function
    is the main entry point that is called and executed.

    :param list sys_args: List of arguments to be parsed by the parser

    :returns: an instance of SystemExit
    :rtype: SystemExit
    """
    ...
