"""
This type stub file was generated by pyright.
"""

from ansible_runner.config._base import BaseConfig

logger = ...

class AnsibleCfgConfig(BaseConfig):
    """
    A ``Runner`` configuration object that's meant to encapsulate the configuration used by the
    :py:mod:`ansible_runner.runner.AnsibleCfgConfig` object to launch and manage the invocation of
    command execution.

    Typically this object is initialized for you when using the standard ``get_ansible_config`` interfaces in :py:mod:`ansible_runner.interface`
    but can be used to construct the ``AnsibleCfgConfig`` configuration to be invoked elsewhere. It can also be overridden to provide different
    functionality to the AnsibleCfgConfig object.

    :Example:

    >>> ac = AnsibleCfgConfig(...)
    >>> r = Runner(config=ac)
    >>> r.run()

    """

    def __init__(self, runner_mode=..., **kwargs) -> None: ...

    _supported_actions = ...
    def prepare_ansible_config_command(
        self, action, config_file=..., only_changed=...
    ): ...
