"""
This type stub file was generated by pyright.
"""

from ansible_runner.config._base import BaseConfig

logger = ...

class CommandConfig(BaseConfig):
    """
    A ``Runner`` configuration object that's meant to encapsulate the configuration used by the
    :py:mod:`ansible_runner.runner.CommandConfig` object to launch and manage the invocation of
    command execution.

    Typically this object is initialized for you when using the standard ``run`_command` interfaces in :py:mod:`ansible_runner.interface`
    but can be used to construct the ``CommandConfig`` configuration to be invoked elsewhere. It can also be overridden to provide different
    functionality to the CommandConfig object.
    :Example:

    >>> cc = CommandConfig(...)
    >>> r = Runner(config=cc)
    >>> r.run()
    """

    def __init__(
        self, input_fd=..., output_fd=..., error_fd=..., runner_mode=..., **kwargs
    ) -> None: ...

    _ANSIBLE_NON_INERACTIVE_CMDS = ...
    def prepare_run_command(self, executable_cmd, cmdline_args=...): ...
