"""
This type stub file was generated by pyright.
"""

from ansible_runner.config._base import BaseConfig

logger = ...

class InventoryConfig(BaseConfig):
    """
    A ``Runner`` configuration object that's meant to encapsulate the configuration used by the
    :py:mod:`ansible_runner.runner.InventoryConfig` object to launch and manage the invocation of
    command execution.

    Typically this object is initialized for you when using the standard ``get_inventory`` interfaces in :py:mod:`ansible_runner.interface`
    but can be used to construct the ``InventoryConfig`` configuration to be invoked elsewhere. It can also be overridden to provide different
    functionality to the InventoryConfig object.

    :Example:

    >>> ic = InventoryConfig(...)
    >>> r = Runner(config=ic)
    >>> r.run()

    """

    def __init__(self, runner_mode=..., **kwargs) -> None: ...

    _supported_response_formats = ...
    _supported_actions = ...
    def prepare_inventory_command(
        self,
        action,
        inventories,
        response_format=...,
        host=...,
        playbook_dir=...,
        vault_ids=...,
        vault_password_file=...,
        output_file=...,
        export=...,
    ): ...
