# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # To monitor pyproject.toml / Poetry.lock files
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # Keep the requirements.txt for Sphinx builds in `/docs` up to date, also.
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
  # For keeping workflows up-to-date.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CI/CD"
    commit-message:
      prefix: ci
