# Set default build options
PYTEST_BOARDWALKD_PERSIST_WORKSPACES_BETWEEN_TESTS ?= False

# Builds module artifacts
.PHONY: build
build: dist

.PHONY: container
container:
	podman build . --tag boardwalk:$$(uv version --short)

# Cleans up temporary data that might get created during normal development
.PHONY: clean
clean:
	set -o pipefail

	@echo '[.] Removing built packages and documentation ...'
	rm -rf dist/
	rm -rf docs/source/_autogenerated/
	rm -rf docs/build/

	@echo '[.] Cleaning __pycache__ directories ...'
	find . -type d -name '__pycache__' | xargs rm -rf

	@echo '[.] Cleaning .boardwalk and .boardwalkd directories ...'
	find . -type d -name '.boardwalk' -or -name '.boardwalkd' | xargs rm -rf

	@echo '[.] Cleaning pytest and ruff caches ...'
	find . -type d -name '.pytest_cache' -or -name '.ruff_cache' | xargs rm -rf

	@echo '[.] Removing podman images for localhost/boardwalk ...'
	podman image rm $$(podman images 'localhost/boardwalk' --quiet) || :

# Installs modules in editable mode
.PHONY: develop
develop:
	uv sync --locked

.PHONY: develop-server
develop-server: develop
ifdef BOARDWALKD_SLACK_WEBHOOK_URL
	uv run --frozen boardwalkd serve \
		--develop \
		--workspace-status-json \
		--host-header-pattern="(localhost|127\.0\.0\.1)" \
		--port=8888 \
		--url='http://localhost:8888' \
		--slack-error-advice-config test/server-client/slack-error-advice.toml
else
	uv run --frozen boardwalkd serve \
		--develop \
		--workspace-status-json \
		--host-header-pattern="(localhost|127\.0\.0\.1)" \
		--port=8888 \
		--url='http://localhost:8888'
endif

# Also runs the server, but loads demo data for UI testing
.PHONY: develop-server-demo
develop-server-demo:
	@echo '[.] Resetting .boardwalkd state ...'
	find . -type d -name '.boardwalkd' | xargs rm -rf
	@echo '[.] Launching boardwalkd with demo data loaded ...'
	BOARDWALKD_DEMO=True $(MAKE) develop-server

dist: clean
	uv build

# Builds the Sphinx HTML documentation -- Shortcut for `cd docs && make html`
.PHONY: docs
docs:
	uv run --frozen --group docs make --directory=./docs/ html

# Applies fixable errors, and formats code
.PHONY: format
format:
	uv run --frozen ruff check --fix
	uv run --frozen ruff format

# Installs/updates JS/CSS dependencies in boardwalkd
BOOTSTRAP_VERSION := 5.2.2
HTMX_VERSION := 1.8.2
.PHONY: install-web-deps
install-web-deps:
	curl "https://unpkg.com/htmx.org@$(HTMX_VERSION)/dist/htmx.min.js" -o src/boardwalkd/static/htmx.min.js
	curl "https://cdn.jsdelivr.net/npm/bootstrap@$(BOOTSTRAP_VERSION)/dist/css/bootstrap.min.css" -o src/boardwalkd/static/bootstrap.min.css
	curl "https://cdn.jsdelivr.net/npm/bootstrap@$(BOOTSTRAP_VERSION)/dist/js/bootstrap.bundle.min.js" -o src/boardwalkd/static/bootstrap.bundle.min.js

# Render all d2 diagrams in ./diagrams to PNG
.PHONY: render-d2
render-d2:
	for file in $$(find ./diagrams -type f -name '*.d2' -not -name '_*.d2'); \
	do \
		d2 $$file $${file%.*}.png; \
	done

# Runs all available tests
.PHONY: test
test: test-pytest test-ruff test-pyright test-semgrep test-ansible-lint

.PHONY: test-ansible-lint
test-ansible-lint:
	uvx --directory test ansible-lint --config-file ansible-lint.yaml z.dummy_playbook_for_ansible_lint.yml server-client/playbooks/

# Run pytest verbosely if we're running manually, but normally if we're in a CI environment.
.PHONY: test-pytest
test-pytest: develop
ifndef CI
	uv run --frozen pytest  --verbose
else
	uv run --frozen pytest
endif

# Same as `test-pytest`, but does not clear the boardwalkd server state between
# test runs (so the workspace state can be inspected after execution)
.PHONY: test-pytest-keep-workspace-state
test-pytest-keep-workspace-state: develop
	PYTEST_BOARDWALKD_PERSIST_WORKSPACES_BETWEEN_TESTS=True uv run --frozen pytest  --verbose

# Run all available Ruff checks
.PHONY: test-ruff
test-ruff: test-ruff-linters test-ruff-formatting

# Run all available Ruff linter checks
.PHONY: test-ruff-linters
test-ruff-linters: develop
	uv run --frozen ruff check

# Run all available Ruff formatting checks
.PHONY: test-ruff-formatting
test-ruff-formatting: develop
	uv run --frozen ruff format --check

# Perform type analysis
.PHONY: test-pyright
test-pyright: develop
	uv run --frozen pyright

# Perform security static analysis
.PHONY: test-semgrep
test-semgrep: develop
	uvx semgrep \
		--config semgrep-rules.yml \
		--config "p/r2c-security-audit" \
		--config "p/r2c-bug-scan" \
		--config "p/secrets" \
		--config "p/dockerfile" \
		--exclude-rule=generic.html-templates.security.var-in-href.var-in-href \
		--metrics off
