name: Python and Poetry Project Setup
description: >
  Installs Poetry, a Python version from 3.11 to 3.13 with Poetry venv caching, then installs the Poetry project.

  Because YAML anchors _still_ aren't implemented. (https://github.com/actions/runner/issues/1182)
inputs:
  python-version:
    description: Which Python version should be installed
    required: true
    default: '3.13'
    type: string
    options:
      - '3.11'
      - '3.12'
      - '3.13'
runs:
  using: composite
  steps:
    # Using the caching mechanism for Poetry provided by `actions/setup-python` requires that Poetry be available beforehand
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        installer-parallel: true

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'  # Use the caching provided by actions/setup-python, since it's included.

    - name: Install the project via Poetry
      run: poetry install --no-interaction
      shell: bash
