vars: {
    d2-config: {
        center: true
        pad: 10
        sketch: true
        theme-id: 101
        theme-overrides: {
            B1: "#590310"  # Red 80
            B2: "#E20626"  # Red 50
            B3: "#E02945"  # Red 40
            B4: "#EC766D"  # Red 30
            B5: "#F2A19B"  # Red 20
            B6: "#F7CFCB"  # Red 10
        }
    }
}
