...@_d2_configuration

direction: right

explanation: |md
# Conceptual Overview Diagram
| { near: top-center }

ws: Workspace {
    wf: Workflow {
        Job1 -> Job2 -> JobN
        JobN.style.multiple: true
    }
}
