---
# Name of this GitHub Actions workflow.
name: Semgrep OSS scan

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep-oss/scan
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0 - https://github.com/actions/checkout/releases/tag/v7.0.0

      - name: Run default job setup (Checkout, uv, python, install project)
        uses: ./.github/actions/project_setup

      - name: Execute semgrep scan command using the Makefile recipe
        run: make test-semgrep
