---
# Name of this GitHub Actions workflow.
name: Semgrep OSS scan

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep-oss/scan
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3 - https://github.com/actions/checkout/releases/tag/v6.0.3

      - name: Run default job setup (Checkout, uv, python, install project)
        uses: ./.github/actions/project_setup

      # Run the "semgrep scan" command on the command line of the docker image.
      - name: Execute semgrep scan command
        run: >
          uv run --frozen semgrep scan --config test/semgrep-rules.yml
          --config "p/r2c-security-audit"
          --config "p/r2c-bug-scan"
          --config "p/secrets"
          --config "p/dockerfile"
          --metrics off
